services:
  db:
    image: postgres:16
    container_name: phishsense-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: phishsense_dev
      POSTGRES_USER: phishsense
      POSTGRES_PASSWORD: qhdks00@@
    ports:
      - "5432:5432"
    volumes:
      - phishsense_pgdata:/var/lib/postgresql/data

volumes:
  phishsense_pgdata:
